(#22) Add health-check:health command
ans-group/laravel-health-check pull request #70
Opened 2022-07-13 09:50 UTC by nick322

Because [#44](https://github.com/ans-group/laravel-health-check/pull/44) hasn't been updated for a long time...
So I have reference to [PR 44](https://github.com/ans-group/laravel-health-check/pull/44) and make some changes
Hope this feature can be updated

2022-09-27 13:38 UTC, Gman98ish commented
Thanks for this @nick322 I'll take a look when I get a sec

2024-07-15 10:16 UTC, phily245 commented
@nick322 I'm now on the case

2024-07-15 12:24 UTC, phily245 requested changes
Some nice refactoring added in here too, I have added a suggestions for visual feedback on success

2024-07-15 12:24 UTC, phily245 commented on src/Commands/StatusCommand.php
> +        return $isOkay ? 0 : 1;
The only change I'd suggest here is adding a success message, as when I used the command I was left wondering if it had broken or it wasn't doing anything. Maybe something like:

```suggestion
        $this->info('All checks passed successfully');

        return $isOkay ? 0 : 1;
```

2024-07-15 12:31 UTC, phily245 commented on src/Controllers/HealthCheckController.php
> +            ->json($body, in_array(Arr::get($body, 'status'), [Status::DEGRADED, Status::OKAY])  ? 200 : 500);
I have just merged another PR which changes this line, here's how it should look now:

```suggestion
            ->json($body, in_array(Arr::get($body, 'status'), [Status::DEGRADED, Status::OKAY])  ? 200 : config('healthcheck.default-problem-http-code', 500));
```

2024-07-15 12:35 UTC, phily245 approved these changes
Thank you for contributing @nick322!

2024-07-15 12:36 UTC, merged